/** Response headers for Lighthouse Best Practices / trust & safety audits. */
export const SECURITY_HEADERS = [
  {
    key: "Strict-Transport-Security",
    value: "max-age=63072000; includeSubDomains; preload",
  },
  {
    key: "X-Frame-Options",
    value: "SAMEORIGIN",
  },
  {
    key: "X-Content-Type-Options",
    value: "nosniff",
  },
  {
    key: "Referrer-Policy",
    value: "strict-origin-when-cross-origin",
  },
  {
    key: "Cross-Origin-Opener-Policy",
    value: "same-origin",
  },
  {
    key: "Cross-Origin-Resource-Policy",
    value: "same-site",
  },
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=(), interest-cohort=()",
  },
  {
    key: "Content-Security-Policy",
    value: [
      "default-src 'self'",
      [
        "script-src 'self' 'unsafe-inline' 'unsafe-eval'",
        "https://www.googletagmanager.com",
        "https://connect.facebook.net",
        "https://sandbox.web.squarecdn.com",
        "https://web.squarecdn.com",
        "https://js.squareupsandbox.com",
        "https://js.squareup.com",
        "https://js.stripe.com",
      ].join(" "),
      [
        "style-src 'self' 'unsafe-inline'",
        "https://sandbox.web.squarecdn.com",
        "https://web.squarecdn.com",
      ].join(" "),
      [
        "img-src 'self' data: blob:",
        "https://www.facebook.com",
        "https://www.google-analytics.com",
        "https://www.googletagmanager.com",
        "https://*.basemaps.cartocdn.com",
        "https://*.tile.openstreetmap.org",
        "https://sandbox.web.squarecdn.com",
        "https://web.squarecdn.com",
      ].join(" "),
      [
        "font-src 'self' data:",
        "https://square-fonts-production-f.squarecdn.com",
        "https://d1g145x70srn7h.cloudfront.net",
      ].join(" "),
      [
        "connect-src 'self'",
        "https://www.google-analytics.com",
        "https://analytics.google.com",
        "https://www.googletagmanager.com",
        "https://connect.facebook.net",
        "https://www.facebook.com",
        "https://mobiledog-salon.com",
        "https://sandbox.web.squarecdn.com",
        "https://web.squarecdn.com",
        "https://pci-connect.squareupsandbox.com",
        "https://pci-connect.squareup.com",
        "https://connect.squareupsandbox.com",
        "https://connect.squareup.com",
        "https://api.stripe.com",
        "https://m.stripe.com",
        "https://m.stripe.network",
      ].join(" "),
      [
        "frame-src 'self'",
        "https://www.facebook.com",
        "https://www.google.com",
        "https://maps.google.com",
        "https://sandbox.web.squarecdn.com",
        "https://web.squarecdn.com",
        "https://js.squareupsandbox.com",
        "https://js.squareup.com",
        "https://js.stripe.com",
        "https://hooks.stripe.com",
        "https://pci-connect.squareupsandbox.com",
        "https://pci-connect.squareup.com",
        "https://connect.squareupsandbox.com",
        "https://connect.squareup.com",
      ].join(" "),
      "object-src 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      "frame-ancestors 'self'",
    ].join("; "),
  },
] as const;
